# OpenXMW 配置文件
# 2023/02/26 00:00

# 将 eula 的值修改为 true 即表明您同意 OpenXMW EULA (https://plugins.openxmw.mkc.icu/p/2-eula)
eula: false
# 最大连接尝试次数
maxConnectTry: 3
# 云数据获取间隔
# 设置过低易导致超时
checkInterval: 1
# 尝试从 .accesskey 文件读取 Access-Token
# 读取失败则根据 communityData 中的配置从本文件或终端获取
# 若启用了 communityData 则优先使用 communityData 中的 Access-Token
readAccessTokenFromFile: true
communityData:
  # 启用则使用配置文件中的社区数据, 否则需要在终端输入社区数据
  enable: false
  # 使用 OpenXMW 的作品 ID
  projectId: Default
  # 作品作者 ID
  userId: Default
  # 任意账号的 Access-Token
  accessToken: Default